### ISSUE TITLE
Getting glitches in between as the middle half renders

### ISSUE THREAD

**Issue by ashoksinghal** [emilsjolander/android-FlipView#46]
Hi emilsjolander,

I am using your library for making an application. And its working very good. But i am having some glitches in between  when the second haff of the next page appears while filpping.

Please give me some solution for that.

Thanks in Advance....

**Comment by ashoksinghal** [comment]
Hi emilsjolander,

Sorry for logging this bug, Actually the library is working perfectly fine. The issue was from my code.

Thanks !! 
Ashok

**Comment by NohaAlMetwally** [comment]
How did you solve it?

**Comment by janoschp** [comment]
I am getting glitches too, it's not from my code.
