### ISSUE TITLE
How to disable dangling of the first page ?

### ISSUE THREAD

**Issue by ishandutta2007** [emilsjolander/android-FlipView#72]

**Comment by ishandutta2007** [comment]
found the solution. it's the peaking feature.

**Comment by tongdong** [comment]
@ishandutta2007 Can you tell me how to solve this problem

**Comment by ishandutta2007** [comment]
Use this API, set once = true
void peakNext(boolean once);

**Comment by tongdong** [comment]
Thank you very much.
